# Generated by Django 4.2.8 on 2023-12-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_friendshiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
